config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'post_versions#index'

    resources :post_versions, except: :destroy do
      member do
        get :edit_decline
        put :approve
        put :decline
      end
    end
  end

  root 'posts#index'

  resources :posts do
    collection do
      post :preview
      put :add_to_favorites
      put :vote

      get '/:state', action: :posts_list, state: /draft|on_moderation|declined/
    end

    resources :comments
  end

  resources :post_versions do
    member do
      put :send_to_moderation
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  resources :users, except: :destroy do
    member do
      get :activate
    end
  end

  get 'login' => 'sessions#new', as: :login
  post 'logout' => 'sessions#destroy', as: :logout

end

app/models/post_version.rb
class PostVersion < ActiveRecord::Base
  include AASM

  STATES_LIST = [:draft, :on_moderation, :declined, :approved]

  belongs_to :user
  has_one :post

  validates :title, :body, presence: true
  validates :title, length: { in: 5..140 }
  validates :body, length: { minimum: 7 }
  validates :decline_reason, presence: true, if: :declined?

  STATES_LIST.each do |state|
    scope state, -> { where(aasm_state: state).order(created_at: :desc) }
  end

  scope :with_state, -> (name) { where(aasm_state: name) }
  scope :current_draft, -> (post_version) { where(inherit_version_id: post_version.id).with_state(:draft) }

  aasm do
    state :draft, initial: true
    state :on_moderation
    state :declined
    state :approved

    event :send_to_moderation do
      transitions from: :draft, to: :on_moderation
    end

    event :decline do
      transitions from: :on_moderation, to: :declined
    end

    event :approve do
      success do
        create_or_update_post!
      end

      transitions from: :on_moderation, to: :approved
    end
  end

  def create_new_post_version!(params)
    params.merge!(inherit_version_id: self.id) if self.approved?

    self.user.post_versions.create!(params)
  end

  def update_current_post_version!(params)
    self.update!(params)
  end

  def update_or_create_post_version!(params)
    if self.draft?
      update_current_post_version!(params)
    else
      create_new_post_version!(params)
    end
  end

  def create_or_update_post!
    if self.inherit_version_id > 0
      post = self.user.posts.find_by(post_version: self.inherit_version_id)
      post.update!(post_version: self)
    else
      self.user.posts.create!(post_version: self)
    end
  end
end

app/controllers/admin/post_versions_controller.rb
module Admin
  class PostVersionsController < Admin::ApplicationController
    before_filter :find_post_version!, only: [:show, :approve, :decline, :edit_decline]

    def index
      @post_versions = PostVersion.where.not(aasm_state: :draft).order(created_at: :desc)
    end

    def show; end

    def approve
      if @post_version.approve!
        redirect_to admin_post_versions_path
      end
    end

    def decline
      @post_version.assign_attributes(post_version_params)

      if @post_version.decline!
        redirect_to admin_post_versions_path
      else
        render :edit_decline
      end
    end

    def edit_decline; end

    private

      def find_post_version!
        @post_version = PostVersion.find(params[:id])
      end

      def post_version_params
        params.require(:post_version).permit(:decline_reason)
      end
  end
end

app/controllers/post_versions_controller.rb
class PostVersionsController < ApplicationController
  before_filter :require_login
  before_filter :find_post_version!, except: :create

  def show; end

  def edit; end

  def create
    @post_version = current_user.post_versions.build(post_version_params)

    if @post_version.save
      redirect_to post_version_path(@post_version)
    else
      render 'posts/new'
    end
  end

  def update
    # TODO: show notification
    if @post_version.on_moderation?
      redirect_to post_version_path(@post_version), notice: 'Can not modify post already was sent on moderation'
      return
    end

    if @post_version.update_or_create_post_version!(post_version_params)
      redirect_to post_version_path(@post_version)
    end
  end

  def send_to_moderation
    if @post_version.send_to_moderation!
      redirect_to '/posts/on_moderation'
    end
  end

  private

    def post_version_params
      params.require(:post_version).permit(:title, :body, :context)
    end

    def find_post_version!
      @post_version = current_user.post_versions.find(params[:id])
    end
end

app/views/admin/post_versions/edit_decline.html.haml
%h2= @post_version.title

= simple_form_for @post_version, url: decline_admin_post_version_path(@post_version), method: :put do |f|
  .form-group
    = f.input :decline_reason, as: :text, input_html: { class: 'form-control' }
  .form-group
    = link_to :back, class: 'btn btn-default' do
      %span.glyphicon.glyphicon-chevron-left
      Back
    = f.button :submit, "Decline", class: 'btn btn-danger'

app/views/admin/post_versions/index.html.haml
%table.table
  %thead
    %tr
      %th
        = PostVersion.human_attribute_name(:id)
      %th
        = PostVersion.human_attribute_name(:title)
      %th
        = PostVersion.human_attribute_name(:aasm_state)
      %th
        = PostVersion.human_attribute_name(:post)

  %tbody
    - @post_versions.each do |post_version|
      %tr
        %td
          = link_to post_version.id, admin_post_version_path(post_version)
        %td #{post_version.title}
        %td
          %span{class: "label #{label_state_class(post_version)}"}
            = post_version.aasm_state

          - if post_version.decline_reason?
            .decline-hint
              %small #{post_version.decline_reason}
        %td
          = current_post_link(post_version)

app/views/admin/post_versions/show.html.haml
.post-version
  .panel.panel-default
    .panel-heading
      .row
        .col-md-1
          = link_to admin_post_versions_path, class: 'btn btn-default btn-xs' do
            %span.glyphicon.glyphicon-chevron-left

        - unless @post_version.declined?
          .col-md-4.col-md-offset-5
          .col-md-1
            = button_to 'Approve', approve_admin_post_version_path(@post_version), method: :put, class: 'btn btn-success btn-xs'
          .col-md-1
            = link_to 'Decline', edit_decline_admin_post_version_path(@post_version), class: 'btn btn-danger btn-xs'

      .row
        .col-md-12
          %h3= @post_version.title

      %hr
      .row
        .col-md-3
          %small
            %strong
              = PostVersion.human_attribute_name(:user)
            %mark #{@post_version.user.email}

      .row
        .col-md-3
          %small
            %strong
              = PostVersion.human_attribute_name(:created_at)
            %mark #{@post_version.created_at}

      .row
        .col-md-3
          %span{ class: "label #{label_state_class(@post_version)}"}
            = @post_version.aasm_state

          - if @post_version.decline_reason?
            .decline-hint
              %small #{@post_version.decline_reason}

    .post-panel.panel-body
      .row
        %p= markdown @post_version.body