config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'post_versions#index'

    resources :post_versions, except: :destroy do
      member do
        get :edit_decline
        put :approve
        put :decline
      end
    end
  end

  root 'posts#index'

  resources :posts do
    collection do
      post :preview
      put :add_to_favorites
      put :vote

      get '/:state', action: :posts_list, state: /draft|on_moderation|declined/
    end

    resources :comments
  end

  resources :post_versions do
    member do
      put :send_to_moderation
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  resources :users, except: :destroy do
    member do
      get :activate
    end
  end

  get 'login' => 'sessions#new', as: :login
  post 'logout' => 'sessions#destroy', as: :logout

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login

  def create
    @user = User.where(email: params[:email]).first

    @user.deliver_reset_password_instructions! if @user

    redirect_to root_path, notice: 'Instructions have been sent to your email.'
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/views/password_resets/edit.html.haml
= simple_form_for @user, url: password_reset_path(@token), defaults: { { input_html: 'form-control' } } do |f|
  .form-group
    = f.input :email, as: :email
  .form-group
    = f.input :password, as: :password
  .form-group
    = f.input :password_confirmation, as: :password
  .form-group
    = f.button :submit, class: 'btn btn-default'

app/views/password_resets/new.html.haml
= simple_form_for password_resets_path, defaults: { input_html: { class: 'form-control' } } do |f|
  .form-group
    = f.input :email
  .form-group
    = f.button :submit, "Reset my password!", class: 'btn btn-default'