config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'post_versions#index'

    resources :post_versions, except: :destroy do
      member do
        get :edit_decline
        put :approve
        put :decline
      end
    end
  end

  root 'posts#index'

  resources :posts do
    collection do
      post :preview
      put :add_to_favorites
      put :vote

      get '/:state', action: :posts_list, state: /draft|on_moderation|declined/
    end

    resources :comments
  end

  resources :post_versions do
    member do
      put :send_to_moderation
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  resources :users, except: :destroy do
    member do
      get :activate
    end
  end

  get 'login' => 'sessions#new', as: :login
  post 'logout' => 'sessions#destroy', as: :logout

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :post_version

  has_many :comments
  has_many :post_votes
  has_many :user_votes, through: :post_votes, source: :user

  def favorites_quantity
    User.favorites_quantity(self.id)
  end

  def rating_quantity
    self.post_votes.map(&:rate).sum
  end

  def owned_by?(user)
    self.user == user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_login, except: [:index, :show]
  before_filter :find_post!, only: [:show, :add_to_favorites, :vote]

  def index
    @posts = Post.includes(:post_version).order(created_at: :desc)
  end

  def show
    @post_json_data = PostSerializer.new(@post, scope: current_user).to_json
  end

  def new
    @post_version = PostVersion.new
  end

  def edit
    @post_version = current_user.posts.find(params[:id]).post_version

    if current_version = current_user.post_versions.current_draft(@post_version).first
      @post_version = current_version
    end
  end

  def posts_list
    @posts = current_user.post_versions.with_state(params[:state])
  end

  def preview
    html_data = MarkdownParser.new(params[:body]).to_html

    render html: html_data
  end

  def add_to_favorites
    if current_user.add_or_drop_favorites!(@post)

      notice, status =
        if current_user.included_in_favorites?(@post)
          [t('ui.small_notifications.favorite_added'), false]
        else
          [t('ui.small_notifications.favorite_removed'), true]
        end
    else
      render nothing: true
    end

    render json: { notice: notice, quantity: @post.favorites_quantity, status: status }
  end

  def vote
    json_data  =
      if current_user.rate_post(@post, params[:rate])
        { notice: t('ui.small_notifications.post_rating.voted') }
      else
        { warning: t('ui.small_notifications.post_rating.already_voted') }
      end

    render json:  json_data.merge(quantity: @post.rating_quantity)
  end

  private

    def find_post!
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.haml
= render 'shared/post_markdown_editor'

app/views/posts/index.html.haml
%h1 Posts

.row
  .col-md-9
    - @posts.each do |post|
      %h3
        = link_to post.post_version.title, post_path(post)
  .col-md-3
    = render 'shared/menu'

app/views/posts/new.html.haml
%h2 Write Post
= render 'form'

app/views/posts/posts_list.html.haml
%ul
  - @posts.each do |post|
    %li
      = link_to post.title, post_version_path(post)

app/views/posts/show.html.haml
.row
  %article.col-md-12
    %header
      %h1
        = @post.post_version.title
    %section
      = markdown @post.post_version.body

%hr
.row
  %post-rating-buttons( post = "#{@post_json_data}" )
  %post-favorite-button( post = "#{@post_json_data}" )

%hr
%comment-box( post-id = "#{@post.id}" )