config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'post_versions#index'

    resources :post_versions, except: :destroy do
      member do
        get :edit_decline
        put :approve
        put :decline
      end
    end
  end

  root 'posts#index'

  resources :posts do
    collection do
      post :preview
      put :add_to_favorites
      put :vote

      get '/:state', action: :posts_list, state: /draft|on_moderation|declined/
    end

    resources :comments
  end

  resources :post_versions do
    member do
      put :send_to_moderation
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets

  resources :users, except: :destroy do
    member do
      get :activate
    end
  end

  get 'login' => 'sessions#new', as: :login
  post 'logout' => 'sessions#destroy', as: :logout

end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Admin Panel
    = include_gon
    = stylesheet_link_tag    'backend', media: 'all'
    = javascript_include_tag 'backend'
    = csrf_meta_tags
  %body
    %header
      %nav.navbar.navbar-default
        .navbar-header
          = link_to 'Admin Panel', admin_root_url, class: 'navbar-brand'
        .collapse.navbar-collapse
          .nav.navbar-nav
            %li
              = link_to 'Post Versions', admin_post_versions_url

          .nav.navbar-nav.navbar-right
            = link_to 'Front page', root_url, class: 'navbar-brand'

    .container
      = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Zvample
    = include_gon
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      %nav.navbar.navbar-default
        .navbar-header
          = link_to 'Zvample', root_url, class: 'navbar-brand'

        .collapse.navbar-collapse
          .nav.navbar-nav
            - if is_current_user_admin?
              %li
                = link_to 'Admin', admin_root_url
            %li
              = link_to 'Posts', posts_url

          .nav.navbar-nav.navbar-right.login-buttons
            - if current_user
              .navbar-text
                = current_user.email

              = link_to 'Write Post', new_post_path, class: 'btn btn-success navbar-btn'
              = link_to 'Edit Profile', edit_user_path(current_user), class: 'btn btn-default navbar-btn'
              = link_to 'Logout', :logout, method: :post, class: 'btn btn-danger navbar-btn'
            - else
              = link_to 'Login', :login, class: 'btn btn-success navbar-btn'
              = link_to 'Register', new_user_path, class: 'btn btn-default navbar-btn'

    .container
      = yield

    = render partial: '/vue_templates'